import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NavBar } from '@/components/nav-bar';
import { cn } from '@/lib/utils';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'hippo',
  description: 'Generated by create next app'
};

type RootLayoutProps = { children: React.ReactNode };

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body
        className={cn('relative h-full font-sans antialiased', inter.className)}
      >
        <main className='relative flex min-h-screen flex-col'>
          <NavBar />
          <div className='flex-1 flex-grow'>{children}</div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
