import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';

import { NavBar } from '@/components/nav-bar';
import { cn } from '@/lib/utils';
import QueryProvider from '@/provider/query-provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'hippo',
  description: 'Generated by create next app'
};

type RootLayoutProps = { children: React.ReactNode };

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={cn('h-full font-sans antialiased', inter.className)}>
        <main className='h-full'>
          <QueryProvider>
            <NavBar />
            <div className='h-full'>{children}</div>
          </QueryProvider>
        </main>
        <Toaster position='top-center' richColors />
      </body>
    </html>
  );
};

export default RootLayout;
